// Teacher

export const TEACHER_LOGIN_REQUEST = "TEACHER_LOGIN_REQUEST";
export const TEACHER_LOGIN_SUCCESS = "TEACHER_LOGIN_SUCCESS";
export const TEACHER_LOGIN_FAIL = "TEACHER_LOGIN_FAIL";
export const TEACHER_LOGOUT = "TEACHER_LOGOUT";

export const TEACHER_CREATE_CLASS_REQUEST = "TEACHER_CREATE_CLASS_REQUEST";
export const TEACHER_CREATE_CLASS_SUCCESS = "TEACHER_CREATE_CLASS_SUCCESS";
export const TEACHER_CREATE_CLASS_FAIL = "TEACHER_CREATE_CLASS_FAIL";
export const TEACHER_CREATE_CLASS_RESET = "TEACHER_CREATE_CLASS_RESET";
export const TEACHER_LIST_CLASSES_REQUEST = "TEACHER_LIST_CLASSES_REQUEST";
export const TEACHER_LIST_CLASSES_SUCCESS = "TEACHER_LIST_CLASSES_SUCCESS";
export const TEACHER_LIST_CLASSES_FAIL = "TEACHER_LIST_CLASSES_FAIL";
export const TEACHER_GET_CLASS_REQUEST = "TEACHER_GET_CLASS_REQUEST";
export const TEACHER_GET_CLASS_SUCCESS = "TEACHER_GET_CLASS_SUCCESS";
export const TEACHER_GET_CLASS_FAIL = "TEACHER_GET_CLASS_FAIL";
export const TEACHER_UPDATE_CLASS_REQUEST = "TEACHER_UPDATE_CLASS_REQUEST";
export const TEACHER_UPDATE_CLASS_SUCCESS = "TEACHER_UPDATE_CLASS_SUCCESS";
export const TEACHER_UPDATE_CLASS_RESET = "TEACHER_UPDATE_CLASS_RESET";
export const TEACHER_UPDATE_CLASS_FAIL = "TEACHER_UPDATE_CLASS_FAIL";
export const TEACHER_DELETE_CLASS_REQUEST = "TEACHER_DELETE_CLASS_REQUEST";
export const TEACHER_DELETE_CLASS_SUCCESS = "TEACHER_DELETE_CLASS_SUCCESS";
export const TEACHER_DELETE_CLASS_FAIL = "TEACHER_DELETE_CLASS_FAIL";

export const TEACHER_CREATE_LESSON_REQUEST = "TEACHER_CREATE_LESSON_REQUEST";
export const TEACHER_CREATE_LESSON_SUCCESS = "TEACHER_CREATE_LESSON_SUCCESS";
export const TEACHER_CREATE_LESSON_FAIL = "TEACHER_CREATE_LESSON_FAIL";
export const TEACHER_CREATE_LESSON_RESET = "TEACHER_CREATE_LESSON_RESET";
export const TEACHER_LIST_LESSONS_REQUEST = "TEACHER_LIST_LESSONS_REQUEST";
export const TEACHER_LIST_LESSONS_SUCCESS = "TEACHER_LIST_LESSONS_SUCCESS";
export const TEACHER_LIST_LESSONS_FAIL = "TEACHER_LIST_LESSONS_FAIL";
export const TEACHER_GET_LESSON_REQUEST = "TEACHER_GET_LESSON_REQUEST";
export const TEACHER_GET_LESSON_SUCCESS = "TEACHER_GET_LESSON_SUCCESS";
export const TEACHER_GET_LESSON_FAIL = "TEACHER_GET_LESSON_FAIL";
export const TEACHER_UPDATE_LESSON_REQUEST = "TEACHER_UPDATE_LESSON_REQUEST";
export const TEACHER_UPDATE_LESSON_SUCCESS = "TEACHER_UPDATE_LESSON_SUCCESS";
export const TEACHER_UPDATE_LESSON_FAIL = "TEACHER_UPDATE_LESSON_FAIL";
export const TEACHER_UPDATE_LESSON_RESET = "TEACHER_UPDATE_LESSON_RESET";

// export const TEACHER_ADD_STUDENT_TO_LESSON_RESET = "TEACHER_ADD_STUDENT_TO_LESSON_RESET";
export const TEACHER_DELETE_LESSON_REQUEST = "TEACHER_DELETE_LESSON_REQUEST";
export const TEACHER_DELETE_LESSON_SUCCESS = "TEACHER_DELETE_LESSON_SUCCESS";
export const TEACHER_DELETE_LESSON_FAIL = "TEACHER_DELETE_LESSON_FAIL";
export const TEACHER_ADD_STUDENT_TO_LESSON_REQUEST =
  "TEACHER_ADD_STUDENT_TO_LESSON_REQUEST";
export const TEACHER_ADD_STUDENT_TO_LESSON_SUCCESS =
  "TEACHER_ADD_STUDENT_TO_LESSON_SUCCESS";
export const TEACHER_ADD_STUDENT_TO_LESSON_FAIL = "TEACHER_UPDATE_LESSON_FAIL";
export const TEACHER_REMOVE_STUDENT_FROM_LESSON_REQUEST =
  "TEACHER_REMOVE_STUDENT_FROM_LESSON_REQUEST";
export const TEACHER_REMOVE_STUDENT_FROM_LESSON_SUCCESS =
  "TEACHER_REMOVE_STUDENT_FROM_LESSON_SUCCESS";
export const TEACHER_REMOVE_STUDENT_FROM_LESSON_FAIL =
  "TEACHER_REMOVE_STUDENT_FROM_LESSON_FAIL";

export const TEACHER_CREATE_RESOURCE_REQUEST =
  "TEACHER_CREATE_RESOURCE_REQUEST";
export const TEACHER_CREATE_RESOURCE_SUCCESS =
  "TEACHER_CREATE_RESOURCE_SUCCESS";
export const TEACHER_CREATE_RESOURCE_FAIL = "TEACHER_CREATE_RESOURCE_FAIL";
export const LIST_RESOURCES = "LIST_RESOURCES";
export const LIST_RESOURCES_SUCCESS = "LIST_RESOURCES_SUCCESS";
export const LIST_RESOURCES_FAIL = "LIST_RESOURCES_FAIL";
export const TEACHER_GET_RESOURCE_REQUEST = "TEACHER_GET_RESOURCE_REQUEST";
export const TEACHER_GET_RESOURCE_SUCCESS = "TEACHER_GET_RESOURCE_SUCCESS";
export const TEACHER_GET_RESOURCE_FAIL = "TEACHER_GET_RESOURCE_FAIL";
export const TEACHER_UPDATE_RESOURCE_REQUEST =
  "TEACHER_UPDATE_RESOURCE_REQUEST";
export const TEACHER_UPDATE_RESOURCE_SUCCESS =
  "TEACHER_UPDATE_RESOURCE_SUCCESS";
export const TEACHER_UPDATE_RESOURCE_FAIL = "TEACHER_UPDATE_RESOURCE_FAIL";
export const TEACHER_DELETE_RESOURCE_REQUEST =
  "TEACHER_DELETE_RESOURCE_REQUEST";
export const TEACHER_DELETE_RESOURCE_SUCCESS =
  "TEACHER_DELETE_RESOURCE_SUCCESS";
export const TEACHER_DELETE_RESOURCE_FAIL = "TEACHER_DELETE_RESOURCE_FAIL";

export const TEACHER_CREATE_STUDENT_REQUEST = "TEACHER_CREATE_STUDENT_REQUEST";
export const TEACHER_CREATE_STUDENT_SUCCESS = "TEACHER_CREATE_STUDENT_SUCCESS";
export const TEACHER_CREATE_STUDENT_FAIL = "TEACHER_CREATE_STUDENT_FAIL";
export const TEACHER_CREATE_STUDENT_RESET = "TEACHER_CREATE_STUDENT_RESET";
export const TEACHER_LIST_STUDENTS_REQUEST = "TEACHER_LIST_STUDENTS_REQUEST";
export const TEACHER_LIST_STUDENTS_SUCCESS = "TEACHER_LIST_STUDENTS_SUCCESS";
export const TEACHER_LIST_STUDENTS_FAIL = "LIST_STUDENTS_FAIL";
export const TEACHER_GET_STUDENT_REQUEST = "TEACHER_GET_STUDENT_REQUEST";
export const TEACHER_GET_STUDENT_SUCCESS = "TEACHER_GET_STUDENT_SUCCESS";
export const TEACHER_GET_STUDENT_FAIL = "TEACHER_GET_STUDENT_FAIL";
export const TEACHER_UPDATE_STUDENT_REQUEST = "TEACHER_UPDATE_STUDENT_REQUEST";
export const TEACHER_UPDATE_STUDENT_SUCCESS = "TEACHER_UPDATE_STUDENT_SUCCESS";
export const TEACHER_UPDATE_STUDENT_FAIL = "TEACHER_UPDATE_STUDENT_FAIL";
export const TEACHER_UPDATE_STUDENT_RESET = "TEACHER_UPDATE_STUDENT_RESET";
export const TEACHER_DELETE_STUDENT_REQUEST = "TEACHER_DELETE_STUDENT_REQUEST";
export const TEACHER_DELETE_STUDENT_SUCCESS = "TEACHER_DELETE_STUDENT_SUCCESS";
export const TEACHER_DELETE_STUDENT_FAIL = "TEACHER_DELETE_STUDENT_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
